[package]
name = "minipix-python"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "minipix"
crate-type = ["cdylib"]

[dependencies]
minipix-core = { path = "../core", version = "0.1.0" }
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py39"] }

[lints]
workspace = true
